# Generated by Django 4.1.1 on 2023-02-22 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVEditorDatasetModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=120)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, max_length=10)),
                ('value', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'test data value',
                'verbose_name_plural': 'current dataset',
                'db_table': 'csv_editor_table',
            },
        ),
    ]
